### ISSUE TITLE
Pass to annotation `Provider` instead of `FromComponent("component name")`

### ISSUE THREAD

**Issue by Olegt0rr** [reagento/dishka#168]
## Motivation

It is inconvenient to use additional strings/constants for the sake of components.

```python
class TelegramProvider(Provider):
    component = "Telegram"
    ...

    @provide(scope=Scope.REQUEST)
    async def get_user(self, telegram_object: TelegramObject) -> User:
        return telegram_object.from_user

@router.message()
async def handler(
    message: Message,
    user: Annotated[User, FromComponent["Telegram"]],
) -> None: ...
```

## Suggestion

It would be convenient to add `MyProvider` to the annotation, and then use its `component` field under the hood of the library.

```python
@router.message()
async def handler(
    message: Message,
    user: Annotated[User, TelegramProvider],
) -> None: ...
```

### Additional

This solution has one more advantage: we get the opportunity to move to the provider in 1 click (e.g. to edit it). 
This is not possible in the current implementation (but it's possible in fastapi.Depends)

This solution also helps to avoid pyCharm bug with brackets highlighting: https://youtrack.jetbrains.com/issue/PY-57155/

**Comment by Tishka17** [comment]
Implementing this will break the ability to multiple dependency graphs for the same target dependencies. In short: there will be no DI(!)

Also, it is not possible to implement, because there can be multiple providers at a same time for single component.

I do not think, `components` is for every day case, it is more a for specific case when we need to isolate subgraphs. Event in those cases, I expect to use them for internal parts of graph and use default component in view functions

**Comment by Olegt0rr** [comment]
> because there can be multiple providers at a same time for single component.

Of course it can be! 
But because visibility is open within the component, nothing prevents any provider associated with the component from passing

This still works as expected, anyway
```python
@router.message()
async def handler(
    message: Message,
    user: Annotated[User, FromComponent[TelegramProvider.component]],
) -> None: ...
```

So I just ask for shortcutting it
